# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 19:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('physics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('otherfile', models.FileField(upload_to='attachments/')),
                ('contributor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['text']},
        ),
        migrations.AlterModelOptions(
            name='demo',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='keyword',
            options={'ordering': ['text']},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['text']},
        ),
        migrations.AddField(
            model_name='photo',
            name='contributor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='note',
            name='contributor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attachment',
            name='demo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physics.Demo'),
        ),
    ]
