# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('physics', '0003_auto_20170629_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='demo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physics.Demo'),
        ),
    ]
