# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physics', '0004_auto_20170629_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.TextField(max_length=2048),
        ),
    ]
