# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physics', '0005_auto_20170704_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='thumbnail',
            field=models.ImageField(editable=False, null=True, upload_to='thumbs/'),
        ),
    ]
