# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 18:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('physics', '0006_photo_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2048)),
                ('contributor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='photo',
            name='caption',
        ),
        migrations.AddField(
            model_name='caption',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physics.Photo'),
        ),
    ]
