# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physics', '0007_auto_20170728_1436'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Caption',
            new_name='PhotoNote',
        ),
        migrations.AddField(
            model_name='photo',
            name='caption',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
