# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-29 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('physics', '0008_auto_20170728_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
