# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('physics', '0012_auto_20170730_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='component',
            old_name='text',
            new_name='name',
        ),
    ]
