# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physics', '0013_auto_20170731_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='demo',
        ),
        migrations.AddField(
            model_name='demo',
            name='components',
            field=models.ManyToManyField(to='physics.Component'),
        ),
        migrations.AlterField(
            model_name='component',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
