# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physics', '0015_auto_20170801_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'ordering': ['text'],
            },
        ),
        migrations.AddField(
            model_name='demo',
            name='tags',
            field=models.ManyToManyField(to='physics.Tag'),
        ),
    ]
