# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physics', '0017_auto_20170802_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='components',
            field=models.ManyToManyField(editable=False, to='physics.Component'),
        ),
        migrations.AlterField(
            model_name='demo',
            name='notes',
            field=models.ManyToManyField(editable=False, to='physics.Note'),
        ),
        migrations.AlterField(
            model_name='demo',
            name='tags',
            field=models.ManyToManyField(editable=False, to='physics.Tag'),
        ),
    ]
