# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import physics.models


class Migration(migrations.Migration):

    dependencies = [
        ('physics', '0018_auto_20170802_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='otherfile',
            field=models.FileField(upload_to=physics.models.get_attachment_path),
        ),
        migrations.AlterField(
            model_name='photo',
            name='imagefile',
            field=models.ImageField(upload_to=physics.models.get_photo_path),
        ),
        migrations.AlterField(
            model_name='photo',
            name='thumbnail',
            field=models.ImageField(editable=False, null=True, upload_to=physics.models.get_thumb_path),
        ),
    ]
